name: WhatsAnApp Builder
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    pythonVersion: 3.13.11

jobs:
    build:
        name: Build for ${{ matrix.os-name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                  - os: ubuntu-latest
                    os-name: Linux Ubuntu
                    artifact-path: dist/WhatsAnApp-Linux
                    artifact-name: WhatsAnApp-Linux
                  - os: windows-latest
                    os-name: Windows
                    artifact-path: dist/WhatsAnApp-Windows.exe
                    artifact-name: WhatsAnApp-Windows
                  - os: macos-latest
                    os-name: MacOS
                    artifact-path: dist/WhatsAnApp-MacOS
                    artifact-name: WhatsAnApp-MacOS
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python ${{ env.pythonVersion }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ env.pythonVersion }}

            - name: Install Qt system dependencies (Linux)
              if: runner.os == 'Linux'
              run: |
                sudo apt update
                sudo apt install -y python3-pip python3-venv xvfb libxcb-cursor0 libxcb-xinerama0 libxkbcommon-x11-0
            
            - name: Install Python dependencies (Windows/MacOS)
              if: runner.os != 'Linux'
              run: |
                python -m pip install --upgrade pip
                pip install -r python/requirements.txt
                
            - name: Install Python dependencies (Linux)
              if: runner.os == 'Linux'
              run: pip install -r python/requirements-linux.txt
            
            - name: Compile with PyInstaller
              run: pyinstaller WhatsAnApp.spec

            - name: Rename Build (Windows)
              if: runner.os == 'Windows'
              run: move dist\WhatsAnApp.exe ${{ matrix.artifact-path }}

            - name: Rename Build (Linux/MacOS)
              if: runner.os != 'Windows'
              run: mv dist/WhatsAnApp ${{ matrix.artifact-path }}

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.artifact-name }}
                path: ${{ matrix.artifact-path }}